@DotNetMessenger.WebAPI_HostAddress = http://localhost:5166

GET {{DotNetMessenger.WebAPI_HostAddress}}/api/users
Accept: application/json

###

POST {{DotNetMessenger.WebAPI_HostAddress}}/api/registration
Content-Type: application/json

{
  "name": "alice",
  "password": "secret"
}

###
